import { BadRequestException, ConflictException, Injectable, NotFoundException, UnprocessableEntityException } from '@nestjs/common';
import { Prisma } from '@bidride/database/generated/client';
import { PrismaService } from '../prisma/prisma.service';
import { assertDomainActive } from '../domains/domain-manifest';
import { validateRecommendation } from './recommendation-validator';
import {
  RecommendationStatus,
  STATUS_TRANSITIONS,
  UniversalRecommendation,
} from './recommendation.types';

// ─── Recommendation Ledger ────────────────────────────────────────────────────
// Stores advisory recommendations and the HUMAN decisions taken on them.
// Adoption records a decision — it executes nothing. Every status change
// writes an immutable ai_recommendation_events row (actor, role, action,
// previous/new status, reason, timestamp).
// The ledger is never financial truth: payloads carry canonical REFERENCES.

export interface LedgerActor {
  actor: string;
  actorRole: string;
}

export interface ListFilters {
  domain?: string;
  status?: RecommendationStatus;
  constitutionTag?: string;
  from?: Date;
  to?: Date;
  /** opaque keyset cursor from a prior page's nextCursor (stable pagination) */
  cursor?: string;
  limit: number;
}

const MAX_PAGE_SIZE = 100;
const DEFAULT_PAGE_SIZE = 25;
const MAX_WINDOW_DAYS = 366;

interface Keyset {
  createdAt: Date;
  id: string;
}

// Cursor = base64("<createdAt ISO>|<id>"). Opaque to callers, stable across
// inserts: keyset over (createdAt DESC, id DESC) so equal-timestamp rows never
// duplicate or skip between pages.
export function encodeCursor(k: Keyset): string {
  return Buffer.from(`${k.createdAt.toISOString()}|${k.id}`, 'utf8').toString('base64url');
}

export function decodeCursor(cursor: string): Keyset {
  const raw = Buffer.from(cursor, 'base64url').toString('utf8');
  const sep = raw.lastIndexOf('|');
  const iso = raw.slice(0, sep);
  const id = raw.slice(sep + 1);
  const createdAt = new Date(iso);
  if (sep < 0 || Number.isNaN(createdAt.getTime()) || !id) {
    throw new BadRequestException('invalid pagination cursor');
  }
  return { createdAt, id };
}
// Expiry scheduling moved to the leader-locked SchedulerService (Phase 3.2)
// — one sweep per window across all replicas.
@Injectable()
export class RecommendationLedgerService {
  constructor(private readonly prisma: PrismaService) {}

  async create(rec: UniversalRecommendation): Promise<{ id: string }> {
    const errors = validateRecommendation(rec);
    if (errors.length > 0) {
      throw new UnprocessableEntityException({ message: 'Recommendation rejected', errors });
    }
    // Domain must be active AND the family declared in its manifest — a
    // manifest violation is a producer bug, reported as 422 not 500.
    let manifest;
    try {
      manifest = assertDomainActive(rec.domain);
    } catch (e) {
      throw new UnprocessableEntityException({ message: 'Recommendation rejected', errors: [(e as Error).message] });
    }
    if (!manifest.families.includes(rec.family)) {
      throw new UnprocessableEntityException({
        message: 'Recommendation rejected',
        errors: [`family "${rec.family}" is not declared in the ${rec.domain} domain manifest (declared: ${manifest.families.join(', ') || 'none'})`],
      });
    }

    const row = await this.prisma.$transaction(async (tx) => {
      const created = await tx.aiRecommendation.create({
        data: {
          domain: rec.domain,
          family: rec.family.slice(0, 100),
          recommendationType: rec.recommendationType.slice(0, 50),
          title: rec.title.slice(0, 200),
          status: 'proposed',
          confidence: new Prisma.Decimal(rec.confidence),
          sampleSize: rec.sampleSize,
          constitutionTags: rec.constitutionTags,
          payload: rec as unknown as Prisma.InputJsonValue,
          canonicalRefs: (rec.canonicalRefs ?? undefined) as Prisma.InputJsonValue | undefined,
          expiresAt: rec.expiresAt ? new Date(rec.expiresAt) : null,
        },
      });
      await tx.aiRecommendationEvent.create({
        data: {
          recommendationId: created.id,
          actor: 'ai-service',
          actorRole: 'system',
          action: 'create',
          previousStatus: null,
          newStatus: 'proposed',
          reason: `generated by ${rec.domain}/${rec.family} ${rec.sourceVersion}`,
        },
      });
      return created;
    });
    return { id: row.id };
  }

  async list(filters: ListFilters) {
    const limit = Math.min(Math.max(1, filters.limit || DEFAULT_PAGE_SIZE), MAX_PAGE_SIZE);
    if (filters.from && filters.to) {
      const days = (filters.to.getTime() - filters.from.getTime()) / 86_400_000;
      if (days < 0 || days > MAX_WINDOW_DAYS) {
        throw new BadRequestException(`date range must be 0..${MAX_WINDOW_DAYS} days`);
      }
    }

    const filterWhere: Prisma.AiRecommendationWhereInput = {
      ...(filters.domain && { domain: filters.domain }),
      ...(filters.status && { status: filters.status }),
      ...(filters.constitutionTag && { constitutionTags: { has: filters.constitutionTag } }),
      ...((filters.from || filters.to) && {
        createdAt: { ...(filters.from && { gte: filters.from }), ...(filters.to && { lte: filters.to }) },
      }),
    };

    // Keyset predicate: everything strictly "after" the cursor in
    // (createdAt DESC, id DESC) order. Equal timestamps are broken by id, so
    // no row is duplicated or skipped between pages.
    const keyset = filters.cursor ? decodeCursor(filters.cursor) : null;
    const where: Prisma.AiRecommendationWhereInput = keyset
      ? {
          AND: [
            filterWhere,
            {
              OR: [
                { createdAt: { lt: keyset.createdAt } },
                { createdAt: keyset.createdAt, id: { lt: keyset.id } },
              ],
            },
          ],
        }
      : filterWhere;

    // Fetch one extra to detect a next page without a second query.
    const rows = await this.prisma.aiRecommendation.findMany({
      where,
      orderBy: [{ createdAt: 'desc' }, { id: 'desc' }],
      take: limit + 1,
      select: {
        id: true, domain: true, family: true, recommendationType: true, title: true,
        status: true, confidence: true, sampleSize: true, constitutionTags: true,
        outcomeScore: true, createdAt: true, expiresAt: true,
      },
    });

    const hasMore = rows.length > limit;
    const items = hasMore ? rows.slice(0, limit) : rows;
    const last = items[items.length - 1];
    const nextCursor = hasMore && last ? encodeCursor({ createdAt: last.createdAt, id: last.id }) : null;

    // `total` is filter-scoped (not cursor-scoped) so the inbox can show a
    // meaningful count; it is a plain count, never a keyset offset.
    const total = await this.prisma.aiRecommendation.count({ where: filterWhere });
    return { items, total, limit, nextCursor };
  }

  async get(id: string) {
    const row = await this.prisma.aiRecommendation.findUnique({
      where: { id },
      include: { events: { orderBy: { createdAt: 'asc' } } },
    });
    if (!row) throw new NotFoundException('Recommendation not found');
    return row;
  }

  markViewed(id: string, actor: LedgerActor) {
    return this.transition(id, 'viewed', actor, 'view', undefined, { allowNoop: true });
  }

  adopt(id: string, actor: LedgerActor, reason: string) {
    this.requireReason(reason);
    // Adoption records the Founder's decision ONLY. Nothing is executed here;
    // any real change goes through its own separately-approved workflow.
    return this.transition(id, 'adopted', actor, 'adopt', reason);
  }

  dismiss(id: string, actor: LedgerActor, reason: string) {
    this.requireReason(reason);
    return this.transition(id, 'dismissed', actor, 'dismiss', reason);
  }

  attachOutcome(id: string, actor: LedgerActor, notes: string) {
    this.requireReason(notes);
    return this.transition(id, 'outcome_pending', actor, 'attach_outcome', notes);
  }

  async scoreOutcome(id: string, actor: LedgerActor, score: number, notes?: string) {
    if (!Number.isFinite(score) || score < 0 || score > 1) {
      throw new BadRequestException('outcome score must be in [0, 1]');
    }
    return this.transition(id, 'outcome_scored', actor, 'score_outcome', notes, {
      extraData: { outcomeScore: new Prisma.Decimal(score), outcomeNotes: notes ?? null },
    });
  }

  /** Expire proposed/viewed recommendations whose expiresAt has passed. */
  async expireSweep(): Promise<{ expired: number }> {
    const stale = await this.prisma.aiRecommendation.findMany({
      where: { status: { in: ['proposed', 'viewed'] }, expiresAt: { lt: new Date() } },
      select: { id: true, status: true },
    });
    let expired = 0;
    for (const row of stale) {
      // Status-guarded: a decision landing between the scan and this update
      // (e.g. an adopt) wins — an adopted recommendation is never clobbered
      // to expired.
      const done = await this.prisma.$transaction(async (tx) => {
        const res = await tx.aiRecommendation.updateMany({
          where: { id: row.id, status: row.status },
          data: { status: 'expired' },
        });
        if (res.count === 0) return false;
        await tx.aiRecommendationEvent.create({
          data: {
            recommendationId: row.id,
            actor: 'ai-service', actorRole: 'system', action: 'expire',
            previousStatus: row.status, newStatus: 'expired',
            reason: 'expiresAt passed',
          },
        });
        return true;
      });
      if (done) expired += 1;
    }
    return { expired };
  }

  private requireReason(reason: string): void {
    if (typeof reason !== 'string' || reason.trim().length < 3) {
      throw new BadRequestException('a reason is required for this decision');
    }
  }

  private async transition(
    id: string,
    to: RecommendationStatus,
    actor: LedgerActor,
    action: string,
    reason?: string,
    opts: { allowNoop?: boolean; extraData?: Prisma.AiRecommendationUpdateManyMutationInput } = {},
  ) {
    return this.prisma.$transaction(async (tx) => {
      const row = await tx.aiRecommendation.findUnique({ where: { id }, select: { id: true, status: true } });
      if (!row) throw new NotFoundException('Recommendation not found');
      const from = row.status as RecommendationStatus;

      if (from === to && opts.allowNoop) return { id, status: to, changed: false };
      if (!STATUS_TRANSITIONS[from]?.includes(to)) {
        throw new ConflictException(`illegal transition ${from} → ${to}`);
      }

      // Status-conditioned update: a concurrent decision that already moved
      // the row conflicts instead of being silently overwritten.
      const res = await tx.aiRecommendation.updateMany({
        where: { id, status: from },
        data: { status: to, ...(opts.extraData ?? {}) },
      });
      if (res.count === 0) {
        throw new ConflictException(`recommendation changed concurrently — retry from its current status`);
      }
      await tx.aiRecommendationEvent.create({
        data: {
          recommendationId: id,
          actor: actor.actor.slice(0, 100),
          actorRole: actor.actorRole.slice(0, 50),
          action,
          previousStatus: from,
          newStatus: to,
          reason: reason?.slice(0, 2000) ?? null,
        },
      });
      return { id, status: to, changed: true };
    });
  }
}
