import { BadRequestException, ConflictException, Injectable, NotFoundException, OnModuleDestroy, OnModuleInit, UnprocessableEntityException } from '@nestjs/common';
import { Prisma } from '@bidride/database/generated/client';
import { PrismaService } from '../prisma/prisma.service';
import { assertDomainActive } from '../domains/domain-manifest';
import { validateRecommendation } from './recommendation-validator';
import {
  RecommendationStatus,
  STATUS_TRANSITIONS,
  UniversalRecommendation,
} from './recommendation.types';

// ─── Recommendation Ledger ────────────────────────────────────────────────────
// Stores advisory recommendations and the HUMAN decisions taken on them.
// Adoption records a decision — it executes nothing. Every status change
// writes an immutable ai_recommendation_events row (actor, role, action,
// previous/new status, reason, timestamp).
// The ledger is never financial truth: payloads carry canonical REFERENCES.

export interface LedgerActor {
  actor: string;
  actorRole: string;
}

export interface ListFilters {
  domain?: string;
  status?: RecommendationStatus;
  constitutionTag?: string;
  from?: Date;
  to?: Date;
  page: number;
  limit: number;
}

const MAX_PAGE_SIZE = 100;
const MAX_WINDOW_DAYS = 366;
const EXPIRE_SWEEP_INTERVAL_MS = 6 * 3600 * 1000;

@Injectable()
export class RecommendationLedgerService implements OnModuleInit, OnModuleDestroy {
  private sweepTimer: ReturnType<typeof setInterval> | null = null;

  constructor(private readonly prisma: PrismaService) {}

  onModuleInit(): void {
    // Expiry runs on a schedule (plus the internal endpoint for manual runs);
    // first sweep shortly after boot so short-lived deploys still expire.
    this.sweepTimer = setInterval(() => void this.expireSweep().catch(() => {}), EXPIRE_SWEEP_INTERVAL_MS);
    setTimeout(() => void this.expireSweep().catch(() => {}), 30_000);
  }

  onModuleDestroy(): void {
    if (this.sweepTimer) clearInterval(this.sweepTimer);
  }

  async create(rec: UniversalRecommendation): Promise<{ id: string }> {
    const errors = validateRecommendation(rec);
    if (errors.length > 0) {
      throw new UnprocessableEntityException({ message: 'Recommendation rejected', errors });
    }
    // Domain must be active AND the family declared in its manifest — a
    // manifest violation is a producer bug, reported as 422 not 500.
    let manifest;
    try {
      manifest = assertDomainActive(rec.domain);
    } catch (e) {
      throw new UnprocessableEntityException({ message: 'Recommendation rejected', errors: [(e as Error).message] });
    }
    if (!manifest.families.includes(rec.family)) {
      throw new UnprocessableEntityException({
        message: 'Recommendation rejected',
        errors: [`family "${rec.family}" is not declared in the ${rec.domain} domain manifest (declared: ${manifest.families.join(', ') || 'none'})`],
      });
    }

    const row = await this.prisma.$transaction(async (tx) => {
      const created = await tx.aiRecommendation.create({
        data: {
          domain: rec.domain,
          family: rec.family.slice(0, 100),
          recommendationType: rec.recommendationType.slice(0, 50),
          title: rec.title.slice(0, 200),
          status: 'proposed',
          confidence: new Prisma.Decimal(rec.confidence),
          sampleSize: rec.sampleSize,
          constitutionTags: rec.constitutionTags,
          payload: rec as unknown as Prisma.InputJsonValue,
          canonicalRefs: (rec.canonicalRefs ?? undefined) as Prisma.InputJsonValue | undefined,
          expiresAt: rec.expiresAt ? new Date(rec.expiresAt) : null,
        },
      });
      await tx.aiRecommendationEvent.create({
        data: {
          recommendationId: created.id,
          actor: 'ai-service',
          actorRole: 'system',
          action: 'create',
          previousStatus: null,
          newStatus: 'proposed',
          reason: `generated by ${rec.domain}/${rec.family} ${rec.sourceVersion}`,
        },
      });
      return created;
    });
    return { id: row.id };
  }

  async list(filters: ListFilters) {
    const limit = Math.min(Math.max(1, filters.limit), MAX_PAGE_SIZE);
    const page = Math.max(1, filters.page);
    if (filters.from && filters.to) {
      const days = (filters.to.getTime() - filters.from.getTime()) / 86_400_000;
      if (days < 0 || days > MAX_WINDOW_DAYS) {
        throw new BadRequestException(`date range must be 0..${MAX_WINDOW_DAYS} days`);
      }
    }

    const where: Prisma.AiRecommendationWhereInput = {
      ...(filters.domain && { domain: filters.domain }),
      ...(filters.status && { status: filters.status }),
      ...(filters.constitutionTag && { constitutionTags: { has: filters.constitutionTag } }),
      ...((filters.from || filters.to) && {
        createdAt: { ...(filters.from && { gte: filters.from }), ...(filters.to && { lte: filters.to }) },
      }),
    };

    const [items, total] = await this.prisma.$transaction([
      this.prisma.aiRecommendation.findMany({
        where,
        orderBy: { createdAt: 'desc' },
        skip: (page - 1) * limit,
        take: limit,
        select: {
          id: true, domain: true, family: true, recommendationType: true, title: true,
          status: true, confidence: true, sampleSize: true, constitutionTags: true,
          outcomeScore: true, createdAt: true, expiresAt: true,
        },
      }),
      this.prisma.aiRecommendation.count({ where }),
    ]);
    return { items, total, page, limit };
  }

  async get(id: string) {
    const row = await this.prisma.aiRecommendation.findUnique({
      where: { id },
      include: { events: { orderBy: { createdAt: 'asc' } } },
    });
    if (!row) throw new NotFoundException('Recommendation not found');
    return row;
  }

  markViewed(id: string, actor: LedgerActor) {
    return this.transition(id, 'viewed', actor, 'view', undefined, { allowNoop: true });
  }

  adopt(id: string, actor: LedgerActor, reason: string) {
    this.requireReason(reason);
    // Adoption records the Founder's decision ONLY. Nothing is executed here;
    // any real change goes through its own separately-approved workflow.
    return this.transition(id, 'adopted', actor, 'adopt', reason);
  }

  dismiss(id: string, actor: LedgerActor, reason: string) {
    this.requireReason(reason);
    return this.transition(id, 'dismissed', actor, 'dismiss', reason);
  }

  attachOutcome(id: string, actor: LedgerActor, notes: string) {
    this.requireReason(notes);
    return this.transition(id, 'outcome_pending', actor, 'attach_outcome', notes);
  }

  async scoreOutcome(id: string, actor: LedgerActor, score: number, notes?: string) {
    if (!Number.isFinite(score) || score < 0 || score > 1) {
      throw new BadRequestException('outcome score must be in [0, 1]');
    }
    return this.transition(id, 'outcome_scored', actor, 'score_outcome', notes, {
      extraData: { outcomeScore: new Prisma.Decimal(score), outcomeNotes: notes ?? null },
    });
  }

  /** Expire proposed/viewed recommendations whose expiresAt has passed. */
  async expireSweep(): Promise<{ expired: number }> {
    const stale = await this.prisma.aiRecommendation.findMany({
      where: { status: { in: ['proposed', 'viewed'] }, expiresAt: { lt: new Date() } },
      select: { id: true, status: true },
    });
    let expired = 0;
    for (const row of stale) {
      // Status-guarded: a decision landing between the scan and this update
      // (e.g. an adopt) wins — an adopted recommendation is never clobbered
      // to expired.
      const done = await this.prisma.$transaction(async (tx) => {
        const res = await tx.aiRecommendation.updateMany({
          where: { id: row.id, status: row.status },
          data: { status: 'expired' },
        });
        if (res.count === 0) return false;
        await tx.aiRecommendationEvent.create({
          data: {
            recommendationId: row.id,
            actor: 'ai-service', actorRole: 'system', action: 'expire',
            previousStatus: row.status, newStatus: 'expired',
            reason: 'expiresAt passed',
          },
        });
        return true;
      });
      if (done) expired += 1;
    }
    return { expired };
  }

  private requireReason(reason: string): void {
    if (typeof reason !== 'string' || reason.trim().length < 3) {
      throw new BadRequestException('a reason is required for this decision');
    }
  }

  private async transition(
    id: string,
    to: RecommendationStatus,
    actor: LedgerActor,
    action: string,
    reason?: string,
    opts: { allowNoop?: boolean; extraData?: Prisma.AiRecommendationUpdateManyMutationInput } = {},
  ) {
    return this.prisma.$transaction(async (tx) => {
      const row = await tx.aiRecommendation.findUnique({ where: { id }, select: { id: true, status: true } });
      if (!row) throw new NotFoundException('Recommendation not found');
      const from = row.status as RecommendationStatus;

      if (from === to && opts.allowNoop) return { id, status: to, changed: false };
      if (!STATUS_TRANSITIONS[from]?.includes(to)) {
        throw new ConflictException(`illegal transition ${from} → ${to}`);
      }

      // Status-conditioned update: a concurrent decision that already moved
      // the row conflicts instead of being silently overwritten.
      const res = await tx.aiRecommendation.updateMany({
        where: { id, status: from },
        data: { status: to, ...(opts.extraData ?? {}) },
      });
      if (res.count === 0) {
        throw new ConflictException(`recommendation changed concurrently — retry from its current status`);
      }
      await tx.aiRecommendationEvent.create({
        data: {
          recommendationId: id,
          actor: actor.actor.slice(0, 100),
          actorRole: actor.actorRole.slice(0, 50),
          action,
          previousStatus: from,
          newStatus: to,
          reason: reason?.slice(0, 2000) ?? null,
        },
      });
      return { id, status: to, changed: true };
    });
  }
}
